# Generated by Django 4.2.21 on 2025-05-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wydruki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('ilosc', models.IntegerField(default=0)),
                ('szt_w_wor', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'wydruki',
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('pracownicy_id', models.AutoField(primary_key=True, serialize=False)),
                ('imie_pracownika', models.CharField(max_length=30)),
                ('nazwisko_pracownika', models.CharField(max_length=30)),
                ('dzial', models.CharField(max_length=30)),
                ('identyfikator', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'pracownicy',
                'unique_together': {('imie_pracownika', 'nazwisko_pracownika')},
            },
        ),
        migrations.CreateModel(
            name='Pobrania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imie_pracownika', models.CharField(max_length=30, null=True)),
                ('nazwisko_pracownika', models.CharField(max_length=30, null=True)),
                ('ilosc', models.IntegerField()),
                ('data_pobrania', models.DateTimeField(auto_now_add=True)),
                ('identyfikator', models.ForeignKey(db_column='identyfikator', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_wydrukow.pracownicy', to_field='identyfikator')),
                ('wydruk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panel_wydrukow.wydruki')),
            ],
            options={
                'db_table': 'pobrania',
            },
        ),
    ]
