# Generated by Django 5.1.3 on 2025-06-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_wydrukow', '0002_wydruki_niski_stan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komponenty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('ilosc', models.IntegerField(default=0)),
                ('szt_w_pidelku', models.IntegerField(default=1)),
                ('niski_stan', models.IntegerField(default=1, help_text='Próg niskiego stanu dla tego komponentu')),
            ],
            options={
                'verbose_name': 'Komponent',
                'verbose_name_plural': 'Komponenty',
                'db_table': 'komponenty',
            },
        ),
        migrations.RemoveField(
            model_name='pobrania',
            name='wydruk',
        ),
        migrations.AlterModelOptions(
            name='pobrania',
            options={'verbose_name': 'Pobranie', 'verbose_name_plural': 'Pobrania'},
        ),
        migrations.AddField(
            model_name='pobrania',
            name='komponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='panel_wydrukow.komponenty'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wydruki',
        ),
    ]
