# Generated by Django 5.1.3 on 2025-06-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_wydrukow', '0003_komponenty_remove_pobrania_wydruk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydruki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('ilosc', models.IntegerField(default=0)),
                ('szt_w_wor', models.IntegerField(default=1)),
                ('niski_stan', models.IntegerField(default=1, help_text='Próg niskiego stanu dla tego produktu')),
            ],
            options={
                'db_table': 'wydruki',
            },
        ),
        migrations.RemoveField(
            model_name='pobrania',
            name='komponent',
        ),
        migrations.AlterModelOptions(
            name='pobrania',
            options={},
        ),
        migrations.AddField(
            model_name='pobrania',
            name='wydruk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='panel_wydrukow.wydruki'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Komponenty',
        ),
    ]
